--[[
Copyright (c) 2016 Jason White

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
]]

local description = [[
Usage: lua embed.lua filename
]]

if not arg or not arg[1] then
  io.stderr:write(description)
  return
end

local filename = arg[1]
local varname = filename:gsub("[/\\%.]", "_")

local content = assert(io.open(filename, "rb")):read("*a")

local numtab = {};

for i=0, 255 do
    numtab[string.char(i)] = ("%3d,"):format(i)
end

local function dump(str)
    return (str:gsub(".", numtab):gsub(("."):rep(80), "%0\n"))
end

io.write(([[
/**
 * This file is automatically generated from the script:
 *
 *      %s
 */
unsigned char %s[] = {
%s
};
]]):format(filename, varname, dump(content)))
